/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package epn.poo.gui.com;

import epn.poo.controller.com.ManejoArchivo;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *Maneja el registro de los jugadores
 * @author santi
 */
public class PanelRegisroJugadores extends javax.swing.JPanel {
    
    private final static String path = "Archivos/jugadores.txt";
    private int numJug;
    ManejoArchivo ma = new ManejoArchivo();
    
    /**
     * comprueba la existencia del archivo y si no existe crea uno
     * @param path
     * @throws IOException 
     */
    private void comprobarTexto(String path) throws IOException{
        File f = new File(path);
        File fp = f.getParentFile();
        if(fp != null && !fp.exists())fp.mkdirs();
        if(!f.exists())f.createNewFile(); 
    }
    /**
     * obtiene los datos de los jugadores y los registra en un txt
     * @throws IOException 
     */
    private void registrarJugadores() throws IOException{
        String j1 = txtNombreJ1.getText().trim();
        String j2 = txtNombreJ2.getText().trim();
        String j3 = txtNombreJ3.getText().trim();
        String j4 = txtNombreJ4.getText().trim();
        
        if(j1.isEmpty() || j1 == null || j2.isEmpty() || j2 == null){
                JOptionPane.showMessageDialog(null, "Error: nombre de algun jugador nulo");
                return;
            }
            
            ma.escribirArchivo(path, j1);
            ma.escribirArchivo(path, j2);
        
        if(numJug == 4){
            if(j3.isEmpty() || j3 == null || j4.isEmpty() || j4 == null){
               JOptionPane.showMessageDialog(null, "Error: nombre de algun jugador nulo");
               return;
            }
            
            ma.escribirArchivo(path, j3);
            ma.escribirArchivo(path, j4);
        }
        
        JOptionPane.showMessageDialog(null, "Jugadores registrados exitosamente!");
    }
    
    /**
     * muestra el registro de jugadores
     * @throws IOException 
     */
    private void mostrarReg() throws IOException{
        ArrayList<String> archivo = ma.obtenerTodos(path);
        StringBuilder sb = new StringBuilder();
        for(String l : archivo){
         sb.append(l).append("\n");
        }
        
        txtAResultados.setText(sb.toString());
    }
    /**
     * Creates new form PanelRegisroJugadores
     */
    public PanelRegisroJugadores(int numJugadores) throws IOException {
        this.numJug = numJugadores;
        comprobarTexto(path);
        initComponents();
        if(numJugadores == 2){
            txtNombreJ3.setEnabled(false);
            txtNombreJ3.setVisible(false);
            lblJ3.setVisible(false);
            txtNombreJ4.setEnabled(false);
            txtNombreJ4.setVisible(false);
            lblJ4.setVisible(false);
        }
        txtAResultados.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombreJ1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombreJ2 = new javax.swing.JTextField();
        txtNombreJ3 = new javax.swing.JTextField();
        lblJ3 = new javax.swing.JLabel();
        txtNombreJ4 = new javax.swing.JTextField();
        lblJ4 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAResultados = new javax.swing.JTextArea();
        btnMostrarReg = new javax.swing.JButton();
        btnListo = new javax.swing.JButton();

        jLabel1.setText("Nombre Jugador 1");

        jLabel2.setText("Nombre Jugador 2");

        lblJ3.setText("Nombre Jugador 3");

        lblJ4.setText("Nombre Jugador 4");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        txtAResultados.setColumns(20);
        txtAResultados.setRows(5);
        jScrollPane1.setViewportView(txtAResultados);

        btnMostrarReg.setText("Mostrar Jugadores Registrados");
        btnMostrarReg.addActionListener(this::btnMostrarRegActionPerformed);

        btnListo.setText("Listo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListo)
                .addGap(0, 28, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblJ3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreJ3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreJ2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblJ4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreJ4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJ3)
                    .addComponent(txtNombreJ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJ4)
                    .addComponent(txtNombreJ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnMostrarReg)
                    .addComponent(btnListo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            registrarJugadores();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnMostrarRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarRegActionPerformed
        try {
            mostrarReg();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex);
        }
    }//GEN-LAST:event_btnMostrarRegActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListo;
    private javax.swing.JButton btnMostrarReg;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJ3;
    private javax.swing.JLabel lblJ4;
    private javax.swing.JTextArea txtAResultados;
    private javax.swing.JTextField txtNombreJ1;
    private javax.swing.JTextField txtNombreJ2;
    private javax.swing.JTextField txtNombreJ3;
    private javax.swing.JTextField txtNombreJ4;
    // End of variables declaration//GEN-END:variables


    public JButton getBtnListo() {
        return btnListo;
    }
}
