/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package epn.poo.gui.com;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author santi
 */
public class PanelComoJugar extends javax.swing.JPanel {

    /**
     * Creates new form PanelComoJugar
     */
    public PanelComoJugar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnReglas = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        jLabel1.setText("Como jugar");

        jLabel2.setText("Este es el tradicional juego del cuartenta, si necesitan saber las reglas del juego pueden presionar el boton");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuarenta.png"))); // NOI18N

        jLabel3.setText("Botones De juego");

        jLabel4.setText("Mano del jugador");

        jLabel5.setText("Mesa");

        btnReglas.setText("Ver Reglas");
        btnReglas.addActionListener(this::btnReglasActionPerformed);

        jLabel6.setText("Luego de seleccionar los jugadores e ingresarlos al sistema, veran la interfaz del juego:");

        jLabel7.setText("Para lanzar una carta simplemente da un click en la carta que desees lanzar y persiona el boton");

        jLabel8.setText("que dice lanzar");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LanzarCarta.png"))); // NOI18N

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClickearCarta.png"))); // NOI18N

        jLabel9.setText("Luego de esto aparecera una pantalla negra indicando el jugador con el siguiente turno. Ojo no sean");

        jLabel10.setText("tramposos 😎, cambien de jugador para que solo el indicado vea la pantalla");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PantallaSiguienteJuga.png"))); // NOI18N

        jLabel11.setText("Ya camiaron de posicion😁?? Cuando el sigiente jugador este listo");

        jLabel12.setText("da un click en el boton que dice continuar abajo de la pantalla negra");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BotonContinuar.png"))); // NOI18N

        jLabel13.setText("Hecho esto, podras ver una carta en la mesa, podras seleccionarla y seleccionar un carta de tu");

        jLabel14.setText("maso, en caso de que, segun las reglas, puedas llevarte dicha carta aparecera el boton \"Llevar Cartas\"");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CartasEnMesa.png"))); // NOI18N
        jButton6.setToolTipText("");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CartaParaLLevar.png"))); // NOI18N

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BotonLLevarCarta.png"))); // NOI18N

        jLabel15.setText("Y listo 😎, ahora sera turno del siguiente jugador, al finalizar cada baraja se mostraran los perros ganados");

        jLabel16.setText("por el carton obtenido");

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManoTerminada.png"))); // NOI18N

        jLabel17.setText("Y asi, ganara el primer equipo que llege a 40 perros. Sin nada mas que decir suerte y que gane el mas arrecho!! 😁👍");

        btnSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(33, 33, 33)
                                .addComponent(btnReglas))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel12))
                                            .addComponent(jLabel11))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)
                        .addGap(38, 38, 38)
                        .addComponent(btnSalir))
                    .addComponent(jLabel14)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(536, 536, 536)
                                .addComponent(jButton6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(34, 34, 34)
                                        .addComponent(jButton9)))
                                .addGap(34, 34, 34)
                                .addComponent(jButton8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(jButton5)
                                .addGap(245, 245, 245)
                                .addComponent(jButton7)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnReglas))
                .addGap(3, 3, 3)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel3)
                        .addGap(66, 66, 66)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton6))
                                    .addComponent(jButton7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton9)
                                            .addComponent(jLabel16)))))
                            .addComponent(jButton4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(btnSalir))
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReglasActionPerformed
        JOptionPane.showMessageDialog(null, reglasDelCuarenta);
    }//GEN-LAST:event_btnReglasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReglas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

String reglasDelCuarenta = "Estas son las reglas del 40\n" +
"1. es un juego de dos o cuatro personas si es de cuatro personas se haran dos equipos de 2 personas\n" +
"2. se conoce como mano a que un jugador baraje y reparta las cartas, cada mano esta compuesta de dos rondas donde el jugador de la mano reparte 5 cartas a cada persona jugador\n" +
"3. el jugador a la izquierda del jugador con mano inicia tirando una carta a mesa\n" +
"4. El juego continua con los jugadores tirando cartas a la mesa\n" +
"5. una ronda termina cuando nadie tiene cartas, el jugador que tenga la mano de ese momento volvera a repartir(si el juego es de 2 jugadores seran cuatro rondas por mano)\n" +
"6. hay dos puntos diferentes a tener en cuenta perros(puntos que te permiten ganar se representan con cartas del 8-10 por los que estas no participan en el reto del juego) y carton(te permite tener mas perros)\n" +
"7. Para obtener mas perros con carton debes acumular mas de 19 al final de la mano en ese punto se empieza a contar desde el 6 y eso es lo que se pasara a los perros si es un numero impar se redondea al par mas sercano\n" +
"7. para aumentar carton se pueden llevar cartas de la mesa con cada carta que te llevas contando como uno\n" +
"7.1 para llevarte una carta de la mesa la que tires debe tener el mismo numero o letra que la que esta en la mesa es ese caso te llevaras la carta de la mesa y la que tiraste de tu maso a tu carton\n" +
"7.2. puedes llevarte mas de una carta de la mesa si 1) es suma: esto refiere a que dos cartas de la mesa sumen la que estas lanzando(no tiene valides en letras), 2) es escalera: se refiere a que hagas una escalera con cartas superiores a la que estas tirando siempre y cunado te la puedas llevar a tu carton ya sea su sumaste o es igual a otra carta\n" +
"8. puedes sumar ma perros por caida, limpia, caida y limpia, y por ronda\n" +
"8.1. caida: si te llevas la carta que el jugador inmediatamente anterior a ti lanzo por que sus numeros son iguales se toma como caida, suma 2 perros\n" +
"8.2 limpia: es cuando al llevarte cartas de la mesa no queda ninguna mas esto se conoce como limpia, suma 2 perros\n" +
"8.3 caida y limpia: suma las condiciones anteriores y suma 4 perros\n" +
"8.4. ronda: significa que el jugador tiene tres cartas del mismo numero o letra en su maso en ese cazo en ese caso suma 2 perros\n" +
"9. gana el jugador o equipo que obtenga 40 perros\n" +
"10. cada mano cuando se termina se pasa al jugador de la derecha,";


public JButton getBtnSalir() {
    return btnSalir;
}
}
