/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package epn.poo.main.com;

import javax.swing.JPanel;
import java.awt.FlowLayout;
import java.util.ArrayList;
import epn.poo.controller.com.Carta;
/**
 *
 * @author HP
 */
public class PanelMesa extends javax.swing.JPanel {

    private ArrayList<Carta> mesa;
    private ArrayList<BotonCarta> botonesMesa;
    private ArrayList<Carta> cartasSeleccionadas;
    /**
     * Creates new form NewJPanel
     */
    public PanelMesa(ArrayList<Carta> mesa) {
        this.mesa = mesa;
        this.botonesMesa = new ArrayList<>();
        this.cartasSeleccionadas = new ArrayList<>();

        setLayout(new FlowLayout(FlowLayout.CENTER, 10, 10));
        refrescarMesa();
    }
    public void refrescarMesa() {
        removeAll();
        botonesMesa.clear();
        cartasSeleccionadas.clear();

        for (Carta c : mesa) {
            BotonCarta boton = new BotonCarta(c);

            boton.addActionListener(e -> manejarSeleccion(boton));

            botonesMesa.add(boton);
            add(boton);
        }

        revalidate();
        repaint();
    }
    private void manejarSeleccion(BotonCarta boton) {
        Carta carta = boton.getCarta();

        if (cartasSeleccionadas.contains(carta)) {
            cartasSeleccionadas.remove(carta);
            boton.setBorderPainted(false);
        } else {
            cartasSeleccionadas.add(carta);
            boton.setBorderPainted(true);
        }
    }
    public ArrayList<Carta> getCartasSeleccionadas() {
        return cartasSeleccionadas;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
